-- DATA DO SISTEMA
	SELECT SYSDATETIME() -- 7 CASAS DECIMAIS EM MILISEGUNDOS
	SELECT GETDATE() -- 3 CASAS DECIMAS EM MILISEGUNDOS
	SELECT CURRENT_TIMESTAMP -- 3 CASAS DECIMAIS EM MILISEGUNDOS

-- DATA EM RELAÇÃO À GREENWICH 
	SELECT SYSDATETIMEOFFSET() -- DATA ATUAL COM A DIFERENÇA PARA A CONVENÇÃO DE GREENWICH 
	SELECT SYSUTCDATETIME() -- DATA DE GREENWICH: 7 CASAS DECIMAIS EM MILISEGUNDOS
	SELECT GETUTCDATE() -- DATA DE GREENWICH: 3 CASAS DECIMAIS EM GREENWICH

-- RETORNA STRING, EM CASO DE MÊS RETORNA O NOME DO MÊS
	SELECT DATENAME(YEAR,GETDATE())
	SELECT DATENAME(MICROSECOND,GETDATE())
	SELECT DATENAME(MINUTE,GETDATE())
	SELECT DATENAME(MONTH,GETDATE())

-- RETORNA UMA DATA, DE ACORDO COM A PARTE DESEJADA 
	SELECT DATEPART(MONTH,GETDATE())
	SELECT DAY(GETDATE())
	SELECT YEAR(GETDATE())

-- RETORNA UMA DATA A PARTIR DAS PARTES DESEJADAS
	SELECT DATEFROMPARTS(2015,9,1)

-- RETORNA RETORNA UMA DATA A PARTIR DE PARTES, COM HORAS MINUTOS, SEGUNDOS, SEGUNDOS E Nº DE CASAS DESEJADAS
	SELECT DATETIME2FROMPARTS(2015,9,1,13,12,11,120,3)

-- DIFERENÇA ENTRE MENOR / MAIOR DATA
	SELECT DATEDIFF(DAY, DATEFROMPARTS(2018,12,1), GETDATE())

-- ADICIONA A PARTE DA DATA DESEJADA, O ACRÉSCIMO E A DATA BASE
	SELECT DATEADD(MONTH, 5, GETDATE())

-- RETORNA 0 / 1: PARA VALIDAR SE É OU NÃO UMA DATA VAIDA
	SELECT ISDATE('2018-01-01')